# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e116f7fa656c8550911474f06dd4407d165e9456dbc15f5c882a908622684e9aca479a978db5b6ac88d47470e0a1675450b5bae66880c2563f24d003260c3309

test:
  secret_key_base: 51c6ec01c24cd89fe6ce263c0060aa9bedd4e49b6b15207a2054efcae8f16cfba35ab3a225a2521e623b2c9fae2a79e7eec948e0ef45214b9dbd4aa7e0ab2c36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
